#!/usr/bin/expect
set USER [lindex $argv 0]
set TARGET [lindex $argv 1]
set PASSWD [lindex $argv 2]
set PORT [lindex $argv 3]
set OPTS [lindex $argv 4]
set SSHKEY [lindex $argv 5]

trap {
	 set rows [stty rows]
	 set cols [stty columns]
	 stty rows $rows columns $cols < $spawn_out(slave,name)
} WINCH

if { $OPTS == "-" } {
 set OPTS ""
}

if {$SSHKEY != "-"} {
  spawn ssh $USER@$TARGET -p $PORT -i $SSHKEY $OPTS
  expect {
   "yes/no" { send "yes\r"; exp_continue }
  }
} else {
  spawn ssh $USER@$TARGET -p $PORT $OPTS
  expect {
   "yes/no" { send "yes\r"; exp_continue }
   "password:" { send "$PASSWD\r" }
  }
}

interact {
  timeout 60 { send " "}
}
